#ifndef CONFIG_H
#define CONFIG_H

#define MAX_NODES 50
#define MAX_ALERTS 200
#define BUFFER_SIZE 512
#define SELECT_TIMEOUT_SEC 1

#define DEFAULT_UDP_PORT 9001
#define DEFAULT_TCP_PORT 9002

#define UMBRAL_TEMP_ALTA 40.0
#define UMBRAL_HUM_ALTA 80.0
#define UMBRAL_CONSUMO_ALTA 80.0
#define UMBRAL_VIBRACION_ALTA 2.8

#define TIMEOUT_INACTIVO_SEC 60

#endif