services:
  telemetry-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: telemetry_server
    ports:
      - "9001:9001/udp"
      - "9002:9002/tcp"
    env_file:
      - ./server/config/server.env.example
    restart: unless-stopped
